module: Kitura-GraphQL
author: Laurent Gaches
github_url: https://github.com/lgaches/Kitura-GraphQL/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Kitura-GraphQL.xcodeproj, -target, GraphQLMiddleware, LIBRARY_SEARCH_PATHS=.build/debug]