matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
  - os: osx
    osx_image: xcode8.1
    sudo: required

before_install:
- git clone https://github.com/IBM-Swift/Package-Builder.git

script:
- ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR"

notifications:
  slack:
    secure: GOg6r2vnjqz/CnnkcPfbQJeAGZLxT8GR2gxG7bkTOo7Ca1rArlv9L4YUbwCOtYsKye+d+abpP31PWcOffplsdb32+5HHS8RbGVY65L/KHvtxkPrk4yCMo2MlvS0svEknPu9sbhnx0E8o7q806BwACZn5NGq2353OAbL5WYvc9jC/g8UnvCtGG5WRT85sDsw2Ctvs5frRd2BXw7huwhidS3/xGwJmHhi/6bI9NXjZRLTkdtQiXX6T08itIdtUFyXvddsMOXPxyORhSM/ACH8klnxDTIq+7UpWKupQ7IzY/hcs7LTuckSly+hDom7VIBtjh2JZX1Cuon7ttUeFF67QDk8YOgnDzUgTZxgSzcHmOTjRN+/vuMpMkt0BsR4Z47sBSWU0ZdD7hw1WfmV6XYXehakk/y9KwB3ZDI2TViX+NOtOHLGRaiQL0ktroqOxEWmocVa7RMwfdR3riBmF8L/Lo3qU0sCIYM6jnkb5Gy4hUtMd9wdhfJlz6iOKCHi6I7uss9Z47Zvk7Ug8C5i9YjN+bSfxuN3xgbZMajLdbtcCuGc7n3tefJZALDxfBwTCRgbYTBu1Q4geA0+tP9gqZ0wiraIQQj+3DgvJalHOC2xex/TL+dqzE+4RT6DLegrCakK2ssp+R71umlUcRKgWEKMVS4Gvsar/0dFspvxrwwQGTg8=

after_success:
  - bash <(curl -s https://codecov.io/bash)